BLOCK_SIZE = 64
SCREEN_WIDTH = BLOCK_SIZE * 20
SCREEN_HEIGHT = BLOCK_SIZE * 10

PLAYER_START_Y = SCREEN_HEIGHT - 100
PLAYER_BOX_WIDTH = 20
PLAYER_BOX_HEIGHT = 40

FLOOR = 'F'
GRASS_FLOOR = 'G'
BRICK_TILE = 'B'
CLOUD = 'C'
MOUNTAIN = 'M'



